[package]
name = "kount_count"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytecount = "0.6"
ignore = "0.4"
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }

[lints]
workspace = true
